### ISSUE TITLE
HDU previews dance left/right during window resizing

### ISSUE THREAD

**Issue by mrawls** [nightlightapp/Nightlight-Issues#3]
When I manually drag the corner of Nightlight to resize the app window, the HDU preview cards move abruptly left or right in an unpredictable manner. In particular, they jump so far right as to be out of view if I make the app window too narrow. If I continue making the window extremely narrow, they jump back to the left. (In the case of 2 HDU preview cards, the second/bottom one appears to fly on top of the first/top one as they both move so far left as to be hidden behind the Sources pane). The present behavior feels erratic and disjoint, and I am forced to let the app use more screen real estate with a larger margin of dead gray space around the HDU preview cards than I'd like.

**Comment by demitri** [comment]
Replaced view with (legacy) NSCollectionView. Things behave now.
